# application-dock.yml (生产docker环境配置)

spring:
  # Redis 配置
  cache:
    redis:
      time-to-live: 3600000 #设置缓存过期时间
  redis:
    host: redis
    port: 6379
    password: fubuki0728anime
    database: 0

# MySQL 配置
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://mysql:3306/anime?serverTimezone=UTC&serverTimezone=GMT%2b8&characterEncoding=utf8
      username: root
      password: fubuki0728anime
  jackson:
    time-zone: GMT+8